### ISSUE TITLE
The title of the last entry in a reference list is always followed by a superfluous + sign.

### ISSUE THREAD

**Issue by lwolter** [Alwinator/asciidoctor-lists#10]
The title of the last entry in a reference list is always followed by a superfluous + sign.

**Comment by Alwinator** [comment]
@lwolter Please add a reproduction code. Are you using the latest version (v1.0.7)? Which asciidoctor version are you using?

**Comment by lwolter** [comment]
Version: asciidoctor-2.0.17
asciidoctor-lists 1.0.7
`
asciidoctorGradleVersion = 3.3.2
asciidoctorjVersion      = 2.5.3
rougeVersion             = 3.28.0
diagramVersion           = 2.2.1
pdfVersion               = 1.6.2
`
`= Indexes

== List of figures
list-of::image[enhanced_rendering=true]

== List of tables
list-of::table[enhanced_rendering=true]

== List of code snippets
list-of::listing[enhanced_rendering=true]
`

**Comment by Alwinator** [comment]
@lwolter Thank you! Please create a repository with your code/bug and a README file (how to start) and send me the link that I can reproduce the bug on my computer.

**Comment by lwolter** [comment]
Sorry, I have only just got around to further testing. Fortunately, I cannot reproduce the problem in my small test documents as well as with some other projects in the same system environment and configuration.
