### ISSUE TITLE
Additional space between the label, counter and title if the line has to be wrapped.

### ISSUE THREAD

**Issue by lwolter** [Alwinator/asciidoctor-lists#11]
When a line is broken and space is inserted, this is also done between the label and the counter and the actual title. Is there a way to disable justification?

```adoc
= Test Index

== First chapter

.table 1
|===
| a | 1
| b | 1
|===

.First long table title folder xyz with long title, longer, longer/then/possible/line/size/xyz, longer then possible line size
|===
| a | 1
| b | 1
|===

.Second long table title folder xyz with long title, longer then possible, longer/then/possible/line/size
|===
| a | 1
| b | 1
|===

.table 4
|===
| a | 1
| b | 1
|===

== List of tables
list-of::table[enhanced_rendering=true]
```

**Comment by Alwinator** [comment]
@lwolter I don't understand your problem. I have rendered your example and I think it looks okay:

![image](https://user-images.githubusercontent.com/39517491/167263414-2551ef56-e7f1-4a6c-be7a-82fd95aa834d.png)

**Comment by Alwinator** [comment]
Closed because of inactivity. Please reopen the issue if it still exists.
