### ISSUE TITLE
INFO: possible invalid reference:

### ISSUE THREAD

**Issue by cgoguyer** [Alwinator/asciidoctor-lists#13]
Hello,

I'm using gradle and asciidoctor-2.0.17 with asciidoctor-lists:1.0.8.
It works fine but I'm getting this INFO message for each link generated (figures and tables). How to correct that or hide these messages?

Thx.

```
Converting /Users/christophe/Documentation/docRA/src/ra.adoc
Aug 09, 2022 7:31:13 PM /Users/christophe/Documentation/docRA/build/.asciidoctorGems/gems/asciidoctor-2.0.17/lib/asciidoctor/converter/html5.rb convert_paragraph
INFO: possible invalid reference: 32a93281-f075-44ac-8fa3-a9dfb218bbb3
Aug 09, 2022 7:31:13 PM /Users/christophe/Documentation/docRA/build/.asciidoctorGems/gems/asciidoctor-2.0.17/lib/asciidoctor/converter/html5.rb convert_paragraph
INFO: possible invalid reference: 111fc065-8fa0-47d3-9989-063e02146337
Aug 09, 2022 7:31:13 PM /Users/christophe/Documentation/docRA/build/.asciidoctorGems/gems/asciidoctor-2.0.17/lib/asciidoctor/converter/html5.rb convert_paragraph
```

**Comment by Alwinator** [comment]
Thanks for the bug report. I will take a look at it next week.

**Comment by Alwinator** [comment]
@cgoguyer This is a new feature of Asciidoctor added in [version 2.0.0](https://github.com/asciidoctor/asciidoctor/blob/63ed24ad0b7c03b2e24133a607c5c1a057fb8569/CHANGELOG.adoc#200-2019-03-22---mojavelinux). Based on the [official documentation](https://docs.asciidoctor.org/asciidoctor/latest/errors-and-warnings/#info) it only indicated that:

> The processor could not validate the internal reference named `<x>`. This message doesn’t definitively indicate a missing reference. Rather, it indicates the reference (i.e., anchor) is not in a location where the reference can be validated.

You cannot turn off this specific warning, however, you can turn off warnings in general by removing the `-w` flag as described [here](https://github.com/asciidoctor/asciidoctor/issues/3030).

**Comment by RandomCore** [comment]
When substituting the references it is checked, if the references are in the ` :refs`  asset, which they don't, if the extension created them (line 49). So plainly adding them to ` :refs`, fixes it:
`document.catalog[:refs][element.id] = element`

**Comment by Alwinator** [comment]
@RandomCore Very good to know! Thank you! It would be cool if you could create a Pull Request for that. ;)

**Comment by RandomCore** [comment]
PR is open
