### ISSUE TITLE
avoid page break after toc

### ISSUE THREAD

**Issue by rdmueller** [Alwinator/asciidoctor-lists#15]
have you already managed to get the toc and lists on the same page when you render a PDF? 
I tried `:toc: macro` but asciidoctor alreays renders a page break before and after the toc...

**Comment by Alwinator** [comment]
I never needed this feature to be honest. However, from the perspective of my plugin it should work without a problem. The `:toc: macro` is part of the official asciidoctor repository, so please ask your question here: https://asciidoctor.zulipchat.com

**Comment by rdmueller** [comment]
Thanx!
