### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by orolhawion** [Alwinator/asciidoctor-lists#16]
Hi,

thanks a lot for your extension. I just integrated it in my project with asciidoctor-maven-plugin. Is there a way to publish the extension to Maven Central for easier usage?

Regards,
Martin

**Comment by Alwinator** [comment]
Hi Martin,
I am glad that you like my extension.

It is okay for me if you publish the package on Maven Central as long as you mention the source (link to this repository).

Publishing something on Maven Central has nothing to do with this plugin, however you can find a tutorial [here](https://www.jetbrains.com/help/space/publish-artifacts-from-a-maven-project.html).

**Comment by Alwinator** [comment]
Will be closed due to inactivity, if it is still relevant, feel free to reopen this issue.

**Comment by orolhawion** [comment]
Thanks for your reply. I do not intent to publish your makings on Maven Central. I think that would be your doing simply because you being the owner you should gain the laurels. If you do not intent do to it I am fine with that. :)

**Comment by Alwinator** [comment]
@orolhawion I see! Unfortunately, there is no official Maven version. However, as mentioned, it would be great if you could publish one! (With a reference to this repo)

That more users could enjoy our work! 😃 

Alwin

**Comment by orolhawion** [comment]
Hi, 

I just want to let you know that I was able to integrate your gem with my maven build, so there is no need to publish to `maven central`. I use `de.saumya.mojo:gem-maven-plugin` which installs the required gem(s) in the build directory to make them available to the build. The build extension `org.torquebox.mojo:mavengem-wagon` is used to enable gem downloads from https://rubygems.org/. Dependencies which reference gems need to have the type `gem`.

Hope this helps.
Martin

**Comment by Alwinator** [comment]
@orolhawion That is great to hear! I will add this to the documentation when I have time! :)
