### ISSUE TITLE
backtick  (monospace literal) not rendered in the "title" for a listing

### ISSUE THREAD

**Issue by ghost** [Alwinator/asciidoctor-lists#23]
When a listing title has [`backtick literal`](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#literals-and-source-code) it isn't rendered but rather just shows up  with tags around it`<code>backtick literal</code>` 

Seeing this:

![Screenshot 2024-04-22 3 32 30 PM](https://github.com/Alwinator/asciidoctor-lists/assets/86068473/51c0ed6f-6a81-47f6-94cd-a53bf46a1e1e)

Hoping to see something like this:

![Screenshot 2024-04-22 4 18 39 PM](https://github.com/Alwinator/asciidoctor-lists/assets/86068473/1c3539f2-658c-4182-bf08-ebdb68dc7d0d)

**Comment by ghost** [comment]
At first glance at the docs,  I didn't think https://github.com/Alwinator/asciidoctor-lists?tab=readme-ov-file#enhanced_rendering-experimental applied to this but I tried and the back-tick code block renders  as expected:

![image](https://github.com/Alwinator/asciidoctor-lists/assets/86068473/41517f53-2c67-4aae-b17b-86f51a142865)

I put a small change #24 in to test this as well if that's useful.  

Thank you for this extension!

**Comment by Alwinator** [comment]
Thanks for checking! I will merge your PR!
