### ISSUE TITLE
References do not work

### ISSUE THREAD

**Issue by RerrerBuub** [Alwinator/asciidoctor-lists#3]
Hi,
thanks for this great plugin. 

I tried to use it at my project, but by using the asciidoctor-lists all references inside of my documentation to tables do not work any more. Only the links at the table lists are points into the documented table.

This was my test document:

// Document header
// This is the document header, it can not contain empty lines!
//Attributes needed for PDF generation
= Table Test

// Which header file contains the code with the tags?
// This is relative to where the main documentation .adoc is located.
== Test

.1stTable
[#myTable]
[cols='a,5a']
|===
h| Parameters
h| Values

| FirstParameter
| 4711
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815
| NextParameter
| 0815

|===

<<<<

== next Chapter
// reference to my table does not work with asciidoctor-lists enabled
Text with reference to <<myTable, my table>>

=== List of tables

element_list::[element=table]

**Comment by Alwinator** [comment]
@RerrerBuub I'm glad you like my plugin! I just published a new version (v1.0.2), which should fix your bug.

**Comment by RerrerBuub** [comment]
Great, thanks for this fast fix
