### ISSUE TITLE
no interaction with Asciidoctor Bibliography

### ISSUE THREAD

**Issue by 345Mathieu543** [Alwinator/asciidoctor-lists#6]
Hi,

Your extension is exactly what I searched for!
Unfortunately I can't refer a literature source with [Asciidoctor Bibliography](https://docs.asciidoctor.org/asciidoc/latest/sections/bibliography/) in the image caption so that it is represented correctly in the table of figures.

![TableOfFigures](https://user-images.githubusercontent.com/92370469/154926508-4bca6f09-59db-4aa6-95e3-014887dac092.png)
*Table of figures with incorrect caption representation*

![TestImage](https://user-images.githubusercontent.com/92370469/154926530-d4011097-3b78-48b9-9968-3314eb7fff28.png)
*Test image with correct caption representation*

![Bibliography](https://user-images.githubusercontent.com/92370469/154926554-2aab9fef-ce5d-414f-abd3-60d3c68122e6.png)
*Bibliography where image caption link refers to*

How to reproduce in Asciidoctor (testFile.adoc):
```
= How to reproduce
:notitle:
:figure-caption: Img

<<<
== Table of Figures
element_list::[element=image]

<<<
:sectnums:
== Test Heading
.test image <<Q1>>
image::.\pics\testImg.png[,100,align="left",caption="Img {counter:Img}: "]

.test image <<Q2>>
image::.\pics\testImg.png[,100,align="left",caption="Img {counter:Img}: "]
:sectnums!:

<<<
[bibliography]
== Bibliography

- [[[Q1,1]]] test image link:https://www.google.com/[]
- [[[Q2,2]]] test image link:https://www.google.com/[]
```
Then I compile with: ```asciidoctor-pdf -r ./lib/asciidoctor-lists.rb testFile.adoc```

I'm not sure if this issue can be resolved in this extension. Let me know what you think ;-)

Kind regards,
Mathieu

**Comment by Alwinator** [comment]
@345Mathieu543 Can you provide me a reproduction / asciidoctor code of your example?

**Comment by 345Mathieu543** [comment]
@Alwinator I just updated my previous post

**Comment by Alwinator** [comment]
@345Mathieu543 Unfortunately, the public asciidoc API does not provide a stable way to access the raw title yet. However, when I have time I can try to implement an unstable workaround by [referencing the instance variable](https://stackoverflow.com/questions/12122736/access-instance-variable-from-outside-the-class). Unfortunately, I am very busy currently, so I don't think that I will have time for it in the next couple of weeks. If you need this feature very crucially you are welcome to submit a Pull Request.

**Comment by Alwinator** [comment]
@345Mathieu543 I have implemented your feature request. There is now an enhanced rendering mode that allows you to render links. You can find an example [here](https://github.com/Alwinator/asciidoctor-lists#enhanced_rendering-experimental). Make sure you installed the latest version (1.0.5) before.

**Comment by 345Mathieu543** [comment]
Thank you for your great work!

**Comment by Alwinator** [comment]
@345Mathieu543 You are welcome! ;)
