### ISSUE TITLE
URLs in the figure caption are encoded using special XML chars

### ISSUE THREAD

**Issue by fbdo** [Alwinator/asciidoctor-lists#7]
Hi Alwin and community,

I came across your extension and it works as intended, but with one catch: If there's a link in the figure caption, in the list of figures generated by this extension, the link is encoded using safe XML chars.

I am using Asciidoc as my source and Docbook as my target, so far I have:

Image in the asciidoc file:
```asciidoc
[#amazon-graph-2008]
.Real-time graph of microservice dependencies at http://amazon.com in 2008
image::chapter-01/microservice_graph_amazon_2008.jpeg[align="center"]
```

List macro in the asciidoc file:
```asciidoc
== Lists of figures

list-of::image[]
```

Resulting docbook:
```xml
<title>Lists of figures</title>
<simpara>
<link linkend="amazon-graph-2008">Figure 2. </link>Real-time graph of microservice dependencies at &lt;link xl:href="http://amazon.com"&gt;amazon.com&lt;/link&gt; in 2008<?asciidoc-br?>
</simpara>
```
As you can see the link in the generated list of figures contain the characters \&lt; and \&gt; instead, what end up not rendering as a proper URL in any output generated afterwards. This is a known issue? Any workarounds available?

**Comment by Alwinator** [comment]
@fbdo If you use the latest version  you can try the [enhanced_rendering](https://github.com/Alwinator/asciidoctor-lists#enhanced_rendering-experimental) option:
```adoc
== Lists of figures

list-of::image[enhanced_rendering=true]
```

**Comment by fbdo** [comment]
Shame on me! How I could not see it. Of course I will close this issue, but may I ask, this looks like a good feature to be active by default, any reasons for not doing it?

**Comment by Alwinator** [comment]
No problem. It is disabled by default because it uses a private variable of the asciidoctor API which might be removed or renamed in the future. I hope they make a public one. They are informed.
