### ISSUE TITLE
Add internal attributes for ifdef

### ISSUE THREAD

**Issue by r0ckarong** [Alwinator/asciidoctor-lists#8]
Could you add some background attributes to the processor that we can check for with ifdef so I can hide empty lists?

For example: 
I have an include file that has the definition of both the list of images and list of tables that should be used commonly throughout our documents. If the list is empty, I don't want it to be included. Now I can do this manually for each document but that is hard to communicate to the users and prone to errors. What I would want is to define a single include file with a check for an attribute like "has_images" or "has_tables" like this:

appendix_include.adoc
```AsciiDoc
== My document include appendix

ifdef::has_tables[]
=== List of tables
list-of::table[]
endif::[]

ifdef::has_images[]
=== List of figures
list-of::images[]
endif::[]
```

**Comment by Alwinator** [comment]
@r0ckarong When I understood correctly, you want to have multiple lists for specific sections in your document, right? Because at the moment the library can only generate lists for the whole document with all included files.

**Comment by r0ckarong** [comment]
Maybe I need to explain the problem a little more.

I am providing templates for various doc authors that are supposed to fill in technical content. They work independently from each other (and from me) and I often don't even see the resulting documents. I provide PDF themes and asciidoc templates for them to work with.

One requirement in the documentation style is to have a list of table and figures. My problem is, I don't know if they have images/tables/code snippets in their document at all. So when I design the template with asciidoctor-lists elements I have to define a section for a listing even if this content is not in the document. Then you will get an empty section "list of images" which looks like it's broken for example.

So my idea was to create a template that "smartly" checks if the element for the sections are even present. I would think having some attributes added to the document before or during rendering could give me something to check against using ifdef and then only include the section if the type of content is in the document.

**Comment by Alwinator** [comment]
@r0ckarong Thank you for describing, but I am not sure if this is even possible to implement with the current asciidoctor extension API, because I would need the rendered document to count the images, however, the variable would be needed before the document is rendered. I have contacted the Asciidoctor developers. ([thread](https://asciidoctor.zulipchat.com/#narrow/stream/279656-dev-.F0.9F.9B.A0.EF.B8.8F/topic/has_images.20.2F.20has_table.20attributes.3F.20Are.20they.20possible.3F/near/280472232))

**Comment by Alwinator** [comment]
@r0ckarong I have implemented the feature! Please see [hide_empty_section](https://github.com/Alwinator/asciidoctor-lists#hide_empty_section). Also, make sure that you are using the latest version ([v1.0.7](https://github.com/Alwinator/asciidoctor-lists/releases/tag/v1.0.7)). Please tell me if it works for you!

**Comment by r0ckarong** [comment]
Works as expected. Thanks for the quick solution!
